# Generated by Django 5.2.9 on 2025-12-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id_kategori', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaKonsultasi',
            fields=[
                ('id_media', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_media', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SumberJawaban',
            fields=[
                ('id_sumber', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_sumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipeKunjungan',
            fields=[
                ('id_tipe', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id_jenis', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konsultasi.kategorilayanan')),
            ],
        ),
    ]
