# Generated by Django 5.2.9 on 2025-12-20 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id_kategori', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategori Layanan',
                'verbose_name_plural': 'Kategori Layanan',
                'db_table': 'kategori_layanan',
            },
        ),
        migrations.CreateModel(
            name='MediaKonsultasi',
            fields=[
                ('id_media', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_media', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Media Konsultasi',
                'verbose_name_plural': 'Media Konsultasi',
                'db_table': 'media_konsultasi',
            },
        ),
        migrations.CreateModel(
            name='SumberJawaban',
            fields=[
                ('id_sumber', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_sumber', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sumber Jawaban',
                'verbose_name_plural': 'Sumber Jawaban',
                'db_table': 'sumber_jawaban',
            },
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id_tamu', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=15)),
                ('instansi_perusahaan', models.CharField(blank=True, max_length=150)),
                ('alamat', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tamu',
                'verbose_name_plural': 'Tamu',
                'db_table': 'tamu',
            },
        ),
        migrations.CreateModel(
            name='TipeKunjungan',
            fields=[
                ('id_tipe', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_tipe', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipe Kunjungan',
                'verbose_name_plural': 'Tipe Kunjungan',
                'db_table': 'tipe_kunjungan',
            },
        ),
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id_jenis', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.PROTECT, related_name='jenis_layanan', to='konsultasi.kategorilayanan')),
            ],
            options={
                'verbose_name': 'Jenis Layanan',
                'verbose_name_plural': 'Jenis Layanan',
                'db_table': 'jenis_layanan',
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ttd_petugas', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Petugas',
                'db_table': 'petugas',
                'indexes': [models.Index(fields=['username'], name='petugas_usernam_f5acb6_idx'), models.Index(fields=['is_active'], name='petugas_is_acti_33d816_idx')],
            },
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_kunjungan', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated: BULAN9999 (contoh: DES0001)', max_length=20)),
                ('tanggal_kunjungan', models.DateField(default=django.utils.timezone.now, help_text='Default hari ini, bisa diganti')),
                ('pertanyaan', models.TextField(blank=True, help_text='Wajib untuk kategori konsultasi')),
                ('jawaban', models.TextField(blank=True, help_text='Diisi petugas untuk konsultasi')),
                ('foto_tamu', models.CharField(blank=True, max_length=255)),
                ('ttd_tamu', models.CharField(blank=True, max_length=255)),
                ('status_selesai', models.BooleanField(default=False)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('id_jenis', models.ForeignKey(db_column='id_jenis', on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.jenislayanan')),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.kategorilayanan')),
                ('id_media', models.ForeignKey(blank=True, db_column='id_media', help_text='Wajib untuk konsultasi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.mediakonsultasi')),
                ('id_petugas', models.ForeignKey(blank=True, db_column='id_petugas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunjungan', to='konsultasi.petugas')),
                ('id_sumber', models.ForeignKey(blank=True, db_column='id_sumber', help_text='Wajib untuk konsultasi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.sumberjawaban')),
                ('id_tamu', models.ForeignKey(db_column='id_tamu', on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.tamu')),
                ('id_tipe', models.ForeignKey(db_column='id_tipe', on_delete=django.db.models.deletion.PROTECT, related_name='kunjungan', to='konsultasi.tipekunjungan')),
            ],
            options={
                'verbose_name': 'Kunjungan',
                'verbose_name_plural': 'Kunjungan',
                'db_table': 'kunjungan',
                'ordering': ['-id_kunjungan'],
            },
        ),
        migrations.AddIndex(
            model_name='jenislayanan',
            index=models.Index(fields=['id_kategori'], name='jenis_layan_id_kate_e239c7_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['tanggal_kunjungan'], name='kunjungan_tanggal_b76c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['status_selesai'], name='kunjungan_status__41d019_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['-id_kunjungan'], name='kunjungan_id_kunj_c45d17_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['id_tipe'], name='kunjungan_id_tipe_2d23a0_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['id_kategori'], name='kunjungan_id_kate_5bd168_idx'),
        ),
        migrations.AddConstraint(
            model_name='kunjungan',
            constraint=models.UniqueConstraint(fields=('tanggal_kunjungan', 'nomor_kunjungan'), name='unique_nomor_kunjungan_per_tanggal'),
        ),
    ]
