# Generated by Django 5.2.9 on 2025-12-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kunjungan',
            name='kunjungan_id_kunj_c45d17_idx',
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['id_kunjungan'], name='kunjungan_id_kunj_602a96_idx'),
        ),
    ]
