# Generated by Django 5.2.9 on 2025-12-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ttd_petugas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id_tamu', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('instansi_perusahaan', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_kunjungan', models.CharField(max_length=20)),
                ('tanggal_kunjungan', models.DateField()),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField(blank=True)),
                ('foto_tamu', models.CharField(max_length=255)),
                ('ttd_tamu', models.CharField(max_length=255)),
                ('status_selesai', models.BooleanField(default=False)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konsultasi.jenislayanan')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konsultasi.kategorilayanan')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='konsultasi.mediakonsultasi')),
                ('sumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='konsultasi.sumberjawaban')),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konsultasi.tipekunjungan')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konsultasi.petugas')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konsultasi.tamu')),
            ],
        ),
    ]
